import { ClerkProvider } from '@clerk/nextjs';
import { dark, light } from '@clerk/themes';
import Header from './components/Header';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Clerk Auth App',
	description: 'Clerk Auth App Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<ClerkProvider
			appearance={{
				baseTheme: light, //dark
			}}>
			<html lang='en'>
				<body className={inter.className}>
					<Header />
					<main className='container mx-auto'>
						<div className='flex items-start justify-center min-h-screen'>
							<div className='mt-20'>{children}</div>
						</div>
					</main>
				</body>
			</html>
		</ClerkProvider>
	);
}
